pull_request_rules:
  # Note: Following setup assumes GitHub `Branch protection rule` is
  # configured appropriately.
  - name: automatic squash-merge when CI passes
    conditions:
      - base=master
      - label=ready-to-merge:squash
      - label!=work-in-progress
    actions:
      merge:
        method: squash
  - name: automatic rebase-merge when CI passes
    conditions:
      - base=master
      - label=ready-to-merge:rebase
      - label!=work-in-progress
    actions:
      merge:
        method: rebase
  - name: automatic merge when CI passes
    conditions:
      - base=master
      - label=ready-to-merge:merge
      - label!=work-in-progress
    actions:
      merge:
        method: merge
