## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.3
before_install:
  - unset JULIA_PROJECT
  - julia -e 'using Pkg; pkg"add https://github.com/tkf/Run.jl"'
install:
  - julia -e 'using Run; Run.prepare_test()'
script:
  - julia -e 'using Run; Run.test()'
notifications:
  email: false

# Do not build branches
# * https://docs.travis-ci.com/user/conditional-builds-stages-jobs
# * https://docs.travis-ci.com/user/conditions-v1
if: branch = master OR tag IS present OR type != push
