## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.1
notifications:
  email: false

script:
  - julia --color=yes --project=. -e 'using Pkg; Pkg.instantiate()'
  - julia --color=yes --project=. -e 'using OrdinaryDiffEq'
