name: Debug some code

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: [1.2.0]
        julia-arch: [x86]
    steps:
      - uses: actions/checkout@v1
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: 'DEBUG: backtick'
        run: julia -e '@show `echo hello`'
