name: Format

on:
  push:
    branches-ignore:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: domluna/JuliaFormatter-action@master
      with:
        args: -v .
